[package]
name = "VanityAddresses"
version = "0.1.0"
authors = ["carlosgj94 <carlosgj94@gmail.com>"]

[dependencies]
eth-secp256k1 = { git = "https://github.com/ethcore/rust-secp256k1" }
rand = "0.4.0"
base58 = "0.1"
rustc-serialize = "0.3"
arrayvec = "0.4.7"
rust-crypto = "0.2.36"
